twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/mail/css': css
    globals:
        imprint: '%env(imprint)%'
        dataPrivacy: '%env(dataPrivacy)%'
        helpUrl: '%env(helpUrl)%'
        helpUrlParticipants: '%env(helpUrlParticipants)%'
        laf_version: '%env(laF_version)%'
        matomo_enable: '%env(matomo_enable)%'
        matomo_id: '%env(matomo_id)%'
        matomo_url: '%env(matomo_url)%'